name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          
      - name: Create virtual environment and install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -e ".[dev]"
          
      - name: Lint with black
        run: |
          source .venv/bin/activate
          uv run black --diff src tests || (echo "Run 'black src tests' locally to fix formatting" && exit 1)
          
      - name: Lint with ruff
        run: |
          source .venv/bin/activate
          uv run ruff src tests
          
      - name: Type check with mypy
        run: |
          source .venv/bin/activate
          uv run mypy src

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10', '3.11']
        
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          
      - name: Create virtual environment and install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -e ".[dev]"
          
      - name: Test with pytest
        run: |
          source .venv/bin/activate
          uv run pytest